name: zcli-action
description: Github Action to deploy Zendesk Apps using ZCLI.
inputs:
  env:
    description: "Environment"
    required: true
<<<<<<< HEAD
    default: "dev"
  path:
    description: "Path to dist directory"
    required: true
    default: "apps/zendesk/dist"
=======
>>>>>>> v1.1.2
runs:
  using: "node16"
  main: "dist/index.js"
